const { GoogleGenerativeAI } = require('@google/generative-ai');
const geminiUsageTracker = require('./geminiUsageTracker');
const { callWithFallback } = require('../utils/geminiErrorHandler');

class GeminiService {
  getModel() {
    const apiKey = process.env.GEMINI_API_KEY;
    const modelName = process.env.GEMINI_MODEL || 'gemini-3.5-flash';
    if (!apiKey) {
      return null;
    }
    if (!this.genAI || this.currentApiKey !== apiKey) {
      this.currentApiKey = apiKey;
      this.genAI = new GoogleGenerativeAI(apiKey);
      this.model = this.genAI.getGenerativeModel({ model: modelName });
    }
    return this.model;
  }

  /**
   * Generates text response using Gemini API with robust token tracking.
   * @param {string} prompt - Prompt to send.
   * @param {string} requirement - Tag name for usage logs ("profile", "suggestions", "explanation", "moodboard").
   * @param {string} [userId] - Optional User ID.
   * @param {string} [endpoint] - Optional endpoint path.
   * @param {boolean} [expectJson] - Whether the prompt expects JSON formatting.
   */
  async generate(prompt, requirement, userId = null, endpoint = '/api/quiz/complete', expectJson = false, imagePart = null) {
    const model = this.getModel();
    if (!model) {
      throw new Error("Gemini API key is unconfigured");
    }

    const apiCall = async () => {
      // 1. Calculate input tokens
      let inputTokens = 0;
      try {
        const inputCount = await model.countTokens(prompt);
        inputTokens = inputCount.totalTokens;
      } catch (err) {
        // Fallback estimation: ~4 chars per token
        inputTokens = Math.ceil(prompt.length / 4);
      }

      // 2. Call Gemini API
      const options = {};
      if (expectJson) {
        options.generationConfig = { responseMimeType: "application/json" };
      }

      const contentParts = imagePart ? [prompt, imagePart] : prompt;
      const result = await model.generateContent(contentParts, options);
      const response = await result.response;
      const responseText = response.text();

      // 3. Calculate output tokens
      let outputTokens = 0;
      try {
        const outputCount = await this.model.countTokens(responseText);
        outputTokens = outputCount.totalTokens;
      } catch (err) {
        outputTokens = Math.ceil(responseText.length / 4);
      }

      // 4. Track and log the call asynchronously (do not block flow)
      geminiUsageTracker.trackCall({
        userId,
        requirement,
        endpoint,
        prompt,
        response: responseText,
        inputTokens,
        outputTokens
      }).catch(err => console.error('Tracker error:', err.message));

      return responseText;
    };

    // Execute with fallback handler
    const rawResult = await callWithFallback(apiCall, requirement);

    if (expectJson && typeof rawResult === 'string') {
      try {
        return this.parseJson(rawResult);
      } catch (e) {
        console.error('[GEMINI JSON ERROR] Failed to parse JSON response:', e.message, rawResult);
        // Fallback directly to the fallback template
        const { FALLBACKS } = require('../utils/geminiErrorHandler');
        return FALLBACKS[requirement];
      }
    }

    return rawResult;
  }

  /**
   * Safely cleans and parses JSON responses generated by the model.
   */
  parseJson(text) {
    let cleanText = text.trim();
    // Remove markdown codeblock tags if they were returned
    if (cleanText.startsWith('```json')) {
      cleanText = cleanText.replace(/^```json\s*/i, '').replace(/\s*```$/, '');
    } else if (cleanText.startsWith('```')) {
      cleanText = cleanText.replace(/^```\s*/, '').replace(/\s*```$/, '');
    }
    return JSON.parse(cleanText.trim());
  }
}

module.exports = new GeminiService();
