const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });
const connectDB = require('../src/config/db');
const Admin = require('../src/models/Admin');
const UserJourney = require('../src/models/UserJourney');

/**
 * Removes journey data generated by the Requirement #17 smoke tests.
 *
 * The userJourneys collection was created by this requirement and contains only
 * smoke-test traffic at this point, so it is cleared wholesale. FeatureSequence
 * docs are intentionally kept — they are seeded reference data, not test noise.
 */
async function run() {
  await connectDB();

  const journeyCount = await UserJourney.countDocuments();
  const { deletedCount } = await UserJourney.deleteMany({});
  console.log(`Deleted ${deletedCount}/${journeyCount} UserJourney documents (smoke-test traffic).`);

  const tempAdmins = await Admin.find({ email: { $regex: /^(smoke-admin-|bundle-test-)/ } });
  for (const a of tempAdmins) {
    console.log('Deleting temp admin:', a.email);
    await Admin.findByIdAndDelete(a._id);
  }

  console.log('Journey test cleanup complete.');
  process.exit(0);
}

run().catch((err) => { console.error(err); process.exit(1); });
